// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNi9DJYmmooCgbzxXra6p7TbOSJzDwIIs',
    appId: '1:832430626481:web:a11ae4cb3a257a160ef490',
    messagingSenderId: '832430626481',
    projectId: 'maxim-a6064',
    authDomain: 'maxim-a6064.firebaseapp.com',
    storageBucket: 'maxim-a6064.appspot.com',
    measurementId: 'G-T7K827EVZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDrVeC_oT2kj3odbGkEbN55AyfsWcgnM',
    appId: '1:832430626481:android:327cd959cb89e9a50ef490',
    messagingSenderId: '832430626481',
    projectId: 'maxim-a6064',
    storageBucket: 'maxim-a6064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZSr4bGFBUtnuoeQLw_dgODdd6TxZ0Xk',
    appId: '1:832430626481:ios:552bdce1983986960ef490',
    messagingSenderId: '832430626481',
    projectId: 'maxim-a6064',
    storageBucket: 'maxim-a6064.appspot.com',
    iosClientId: '832430626481-vp8am3e0gjog4n26rmmhslunn52hkf79.apps.googleusercontent.com',
    iosBundleId: 'com.example.maximOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZSr4bGFBUtnuoeQLw_dgODdd6TxZ0Xk',
    appId: '1:832430626481:ios:942377649af9f6790ef490',
    messagingSenderId: '832430626481',
    projectId: 'maxim-a6064',
    storageBucket: 'maxim-a6064.appspot.com',
    iosClientId: '832430626481-dfsr8q64s5lgv5gckev9bp5oujolp27u.apps.googleusercontent.com',
    iosBundleId: 'com.example.maximOrderingApp.RunnerTests',
  );
}
